---
resources:
- name: auroqueue-repo
  type: git
  source:
    uri: https://github.com/2color/auroqueue
    branch: master

- name: auroqueue-docker-image
  type: docker-image
  source:
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: 2color/auroqueue

jobs:
- name: auroqueue
  public: false
  plan:
  - get: auroqueue-repo
    trigger: true
  - task: install node_modules
    config:
      inputs:
        - name: auroqueue-repo
      caches:
        - path: auroqueue-repo/node_modules
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: node
          tag: 8
      run:
        path: auroqueue-repo/ci/install.sh
      outputs:
        - name: src
  - task: unit tests
    config:
      inputs:
        - name: src
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: node
          tag: 8
      run:
        path: npm
        dir: src
        args: ["test"]
  - put: auroqueue-docker-image
    params:
      build: auroqueue-repo/
