---
resources:
- name: auroqueue-app
  type: git
  source:
    uri: https://github.com/2color/auroqueue

jobs:
- name: job-test-autoqueue
  public: false
  plan:
  - get: auroqueue-app
    trigger: true
  - task: auroqueue-test
    file: auroqueue-app/ci/test.yml
